### ISSUE TITLE
Unable to open .lumi file

### ISSUE THREAD

**Issue by Stephlabaraque** [Lumieducation/Lumi#1261] opened 2021-02-19 17:07 UTC
Lumi analytic refuse to open a .lumi file, no file can be imported.

**Comment by sr258** [comment] 2021-02-22 07:36
Can you give more details? How do you try importing the .lumi file? Are you doing it in the analytics tool?

**Comment by Stephlabaraque** [comment] 2021-02-22 08:38
I use Lumi 0.5. Here are the steps:
- Import of a h5p file
- Export in .html  => Do you want to include a reporter in your html?
Learn more about it here. => YES
- Open .html with firefox => Name => toto => save .lumi file
- Doing the exercise
- Save again the .lumi file
- Open Lumi Analytics => import .lumi files => I can't select anything (on linux and windows), a window is opening to select a file, but I can't click on anything, .lumi file or not (can't open directory too) and I have a warning "No valid file selected"

**Comment by sr258** [comment] 2021-02-23 06:42
Thank you for the details. I can confirm that this issue also exists on my Linux machine here. We'll look into it!

**Comment by clintlalonde** [comment] 2021-02-23 21:19
Same issue here using Lumi 0.5 on Windows 10. When I click "Import .lumi files" the Windows file explorer opens into folder view and prompts me to select a folder instead of pick a file.  
![image](https://user-images.githubusercontent.com/679506/108909725-bf229600-75d9-11eb-92f1-043137892fa9.png)

**Comment by JPSchellenberg** [comment] 2021-02-23 22:11
Thank you for the issue. I will look into that.

**Comment by LuVo1924** [comment] 2021-02-25 11:17
Same for me. The entire folder (shown as empty) can be selected ["select Folder"]. The participants' .lumi files are analyzed, but they all got it wrong.
![grafik](https://user-images.githubusercontent.com/79639307/109145712-23bd2c80-7763-11eb-8be3-8fe7e907f327.png)

**Comment by JPSchellenberg** [comment] 2021-02-25 18:43
> Same for me. The entire folder (shown as empty) can be selected ["select Folder"]. The participants' .lumi files are analyzed, but they all got it wrong.

This is related to #1277

**Comment by sr258** [comment] 2021-03-17 06:06
Caused by analyticRoutes:28

**Comment by sr258** [comment] 2021-04-06 09:25
Should be fixed in the last release.

**Closed as completed by sr258** 2021-04-06 09:25 UTC
Labels: [type] bug
