### ISSUE TITLE
Opt-in into sentry.io?

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#1040] opened 2020-12-04 08:11 UTC
Currently, when the Lumi is called, sentry.io is contacted. I understand that Lumi is still in an early stage of development and Sentry is helping with development and reporting of errors. My understanding of the GDPR however is that the use of Sentry requires explanation and that a permission must be obtained for use. Are there plans to change this process to a Opt-In?

**Comment by pheraph** [comment] 2020-12-04 08:12
Relates to #644 I think.

**Comment by sr258** [comment] 2020-12-04 08:13
Yes, you're right. This is something that's on the immediate roadmap. The privacy policy is already finished but must be linked in the app: https://next.lumi.education/app/privacy-policy

**Comment by sr258** [comment] 2020-12-04 11:12
Duplicate of #246

**Closed as completed** 2020-12-04 21:26 UTC
Labels: [type] feature
