### ISSUE TITLE
'No content types available' on Mac M1 / BigSur 11.5.2

### ISSUE THREAD

**Issue by remcoNL** [Lumieducation/Lumi#1878] opened 2021-10-01 08:07 UTC
![image](https://user-images.githubusercontent.com/19585042/135586645-7883be35-6002-4399-982c-369f4e356574.png)

I get this error when opening the H5P editor selecting new H5P. No content types are loaded. Internet connection is fine.

**Comment by sr258** [comment] 2021-10-01 08:27
This might possibly be caused by an outage / overload of h5p.org. We've seen this in the past and might have to move to our own content type hub to avoid this. Please check again in a few hours / tomorrow. You can still download .h5p files from h5p.org and open them in Lumi to install them.

**Comment by JPSchellenberg** [comment] 2021-10-01 12:49
That also might relate to #1879 . It looks like the `api.h5p.org` certificate has expired.

**Comment by cgiess** [comment] 2021-10-01 21:35
I get the same error message on Linux.
The certificate is valid until 2021-11-07 and https://api.h5p.org/v1/sites loads without problems in Chrome and Firefox.

**Comment by JPSchellenberg** [comment] 2021-10-09 21:38
This was resolved in 0.8.2

**Closed as completed by JPSchellenberg** 2021-10-09 21:38 UTC
