### ISSUE TITLE
H5P drag question background image invisible

### ISSUE THREAD

**Issue by tweinreich** [Lumieducation/Lumi#1618] opened 2021-06-10 18:31 UTC
**Describe the bug**
When creating a course presentation and using a "drag question" on a slide the background image after an import into moodle is invisible.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Lumi Version 0.7.2
 - Moodle Version 3.9.4

**To Reproduce**
1. Create a course presentation in Lumi
2. Add a slide
3. Add a drag question onto the slide
4. Add a background image
5. Export as SCORM package (ZIP)
6. Upload to Moodle

**Expected behavior**
The background image should be displayed as it does when using H5P inside Moodle directly.

**Screenshots**
- created directly inside Moodle with the H5P plugin:
<img width="1006" alt="Screenshot 2021-06-10 at 20 15 01" src="https://user-images.githubusercontent.com/4059641/121576358-960eff80-ca28-11eb-8ea6-174ccd26314b.png">
- created with Lumi and uploaded to Moodle:
<img width="1187" alt="Screenshot 2021-06-10 at 20 16 51" src="https://user-images.githubusercontent.com/4059641/121576613-d5d5e700-ca28-11eb-8bcd-acf64606cdff.png">

**Additional context**
I looked at the rendered HTML and found the following issue:
- the `<div class="h5p-inner" role="application"...>` misses the `style='background-image: url("https://...")'` attribute

**Comment by sr258** [comment] 2021-06-11 11:38
Thank you for reporting this issue! I'll look into the cause of it.

**Comment by tweinreich** [comment] 2021-06-11 12:55
Hey @sr258, you're welcome, thank you for looking into it!

**Comment by sr258** [comment] 2021-07-23 09:30
It took some time, but the problem should be fixed in 0.8.0-beta6 (https://github.com/Lumieducation/Lumi/releases/tag/v0.8.0-beta.6)

**Closed as completed by sr258** 2021-07-23 09:30 UTC
Labels: [type] bug

**Comment by tweinreich** [comment] 2021-07-23 09:38
Thank you so much for your time and effort @sr258! 
I will test the new beta asap.
